// packages/types/src/sessions.ts — Zod schemas + TypeScript types for sessions & messages

import { z } from "zod";

// ── Message ───────────────────────────────────────────────────────────────────

export const MessageRoleSchema = z.enum(["user", "assistant", "system", "tool"]);
export type MessageRole = z.infer<typeof MessageRoleSchema>;

export const MessageSchema = z.object({
  id: z.string().uuid(),
  session_id: z.string().uuid(),
  role: MessageRoleSchema,
  content: z.unknown(), // jsonb — AI SDK message parts (flexible)
  tool_calls: z.unknown().nullable().optional(),
  created_at: z.string(),
});
export type Message = z.infer<typeof MessageSchema>;

// Input shape for appending messages — id/created_at auto-generated by DB
export const AppendMessageInputSchema = z.object({
  role: MessageRoleSchema,
  content: z.unknown(),
  tool_calls: z.unknown().optional(),
});
export type AppendMessageInput = z.infer<typeof AppendMessageInputSchema>;

// ── Session ───────────────────────────────────────────────────────────────────

export const SessionSchema = z.object({
  id: z.string().uuid(),
  user_id: z.string(),
  title: z.string().nullable(),
  openclaw_session_id: z.string().nullable().optional(),
  created_at: z.string(),
  updated_at: z.string(),
});
export type Session = z.infer<typeof SessionSchema>;

// Session with hydrated messages (returned by getSession)
export const SessionWithMessagesSchema = SessionSchema.extend({
  messages: z.array(MessageSchema),
});
export type SessionWithMessages = z.infer<typeof SessionWithMessagesSchema>;

// ── API input schemas (used in route handlers) ────────────────────────────────

export const CreateSessionBodySchema = z.object({
  userId: z.string().optional(),
});
export type CreateSessionBody = z.infer<typeof CreateSessionBodySchema>;

export const ListSessionsQuerySchema = z.object({
  userId: z.string().optional(),
  limit: z.coerce.number().int().min(1).max(100).default(20),
});
export type ListSessionsQuery = z.infer<typeof ListSessionsQuerySchema>;
